### ISSUE TITLE
Some questions about the sub-sampled setting

### ISSUE THREAD

**Issue by ddghjikle** [korawat-tanwisuth/Proto_DA#2]
Hi, thanks very much for sharing this wonderful work. According to experimental details in the paper, the sub-sampled setting is similar to the partial-set DA and open-set DA. Is that true? By the way, is there any possibility that codes related to the multi-source setting can also be released?

**Comment by korawat-tanwisuth** [comment]
Thank you for your interest in our work! The sub-sample setup is still a closed-set UDA setting. The categories between source and target remain the same. However, the proportions of classes are skewed (not uniform). The code provided can directly be used for the multi-source setting. You can use Concat dataset to combine the source data into one data loader.
